spring:
  application:
    name: wallet-api

  datasource:
    url: jdbc:mysql://localhost:3306/wallet_db
    username: root
    password: theburgery
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
      tagsSorter: alpha
      doc-expansion: none
      display-request-duration: true

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:test}
    password: ${MAIL_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  wallet:
    transaccion:
      minutos-expiracion: 15

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html